language: r
dist: trusty
sudo: false
before_install:
  # This workaround is required to avoid libstdc++ errors while
  # running "extended" hugo with SASS support.
  - wget -q -O libstdc++6
    http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6
install:
  - wget -q -O hugo.deb
    https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_extended_0.54.0_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
  
branches:
  only:
  - master
  
cache:
  packages: true
  directories:
  - "$HOME/bin"
  
before_script:
- Rscript -e 'blogdown::install_hugo()'

script:
- Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local_dir: public
env:
  global:
    secure: Z8T6TjW7uiCWTNrpceqqB39ZnQXxrxFT120EpyrGn5Ug6TdqNbjxXy4HtU6IUWHXHcrGhTyN4fOVd962i4/k39F7tshFXvNNF+CkOoVHDObEDx95uiiged0HGkrej4YxtTn7EYPWM6/Thi6KHUc7vaRRVBa3EeJ10kX42aSstlCdLH13uSGkaVEuHK6in35jA35TxZITbD0Me3LEF+RxCKZQP7+hcrQNsOGjas6zTBwPOuatJVDDL2dpl4OViPSkQYSTVWI5HrBZfMSd8oEDrnQjrdq7rBPjiphDA3Yy+5oRByAuVgJ7vglic3EgaRitijCZeHtHn3fSP0St3iFGyzhz8jRnNgxGLvOWcg3CSNQaOuP5rI5PtdfyjhvPx+6M/p0yOiMB1DY91Y6juE3J6bR+9DuMYb1Q41i3AukByxInVaq7esC4wWiKTnZM5DG+TxYUB2lA5GAhNyyAFMD1kSbvVcKT0LyBw0Qhm6hJ9UnD1IxUOTF5nzoLdjML68J7u/m86/beAB5ubSjO8nF+xby/5sFZk1W1EakfofD3dVcDbTi+DLxDBfcCkadYwQ7RaUQwempul2ucYFORuEfqvM8Pw6LWPzjJ8CH4IzgzdCJ5ZaUrzHsvINYpcUSQLkmsspmd+4U0p4mnnxxyycX0/x49NmuEK75J5AT9F10KphA=
