name: Render and Deploy RMarkdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Stan, Python, R packages and Deps
        run: |-
         apt-get update \
          && apt-get install -y --no-install-recommends \
          r-cran-rstan \
          r-cran-brms \
          r-cran-coda \
          r-cran-dplyr \
          r-cran-furrr \
          r-cran-ggmcmc \
          r-cran-ggplot2 \
          r-cran-ggthemes \
          r-cran-here \
          r-cran-htmltab \
          r-cran-janitor \
          r-cran-knitr \
          r-cran-leaflet \
          r-cran-magrittr \
          r-cran-microbenchmark \
          r-cran-readr \
          r-cran-reticulate \
          r-cran-tibble \
          r-cran-lubridate \
          python3-venv \
          curl \
          default-jdk \
          libxml2-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          && apt-get clean \
          && rm -rf /var/lib/apt/lists/

      - name: Install Ammonite
        run: |-
          sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.0.4/2.12-2.0.4) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'
      - name: Run Scala examples
        run: |-
          ./notebooks/run_scala.sh
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "pkgbuild::build(path = '.', dest_path = '.'); install.packages('jonnylaw_0.1.0.tar.gz', type = 'source', repos = NULL)"
      - name: Render Site
        run: |-
          Rscript -e "blogdown::build_site()"
          echo "::set-env name=DEPLOY_PATH::'docs'"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: $DEPLOY_PATH
          GH_PAT: ${{ secrets.GH_PAT }}
    container: rocker/r-apt:disco
